#pragma config(Sensor, S2,     color,          sensorCOLORFULL)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int colors[3] = {0,0,0};
task main()
{
	while(true)
	{
		getColorSensorData(color, colorAtoD, colors );
		wait1Msec(10);
	}
}
